[package]
name = "muxlane-client"
version.workspace = true
edition.workspace = true

[dependencies]
muxlane-core = { path = "../muxlane-core" }
muxlane-store = { path = "../muxlane-store" }
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde_json.workspace = true
ulid.workspace = true
tracing.workspace = true
serde.workspace = true
flate2 = "1.0"
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true
sha2.workspace = true
muxlane-server = { path = "../muxlane-server" }
